name: Pull Request Workflow
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ensure this matches the Python version you're using
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest  # Assuming pytest is also used for unit tests
      - name: Lint with flake8
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint  # This ensures that linting passes before running tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: pytest tests/  # Ensure your tests are in the 'tests' directory