name: Pull Request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto-approve
        uses: hmarr/auto-approve-action@v2
        if: contains(fromJson('["t-richielee_microsoft", "Richie-Lee"]'), github.actor)
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: auto-approve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
