name: Pull Request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
