name: Pull Request Workflow
on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 .
      - name: Run tests with pytest
        run: pytest tests/

  experiment:
    runs-on: ubuntu-latest
    needs: lint-and-test
    environment: development
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: List files in the development data directory
        run: ls -la experimentation
      - name: Train model on dev data
        run: python src/model/train.py --training_data experimentation --reg_rate 0.01
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  production:
    runs-on: ubuntu-latest
    needs: experiment
    if: success()
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: List files in the production data directory
        run: ls -la production
      - name: Train model on prod data
        run: python src/model/train.py --training_data production --reg_rate 0.01
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
